question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    # New questions below:
    {"text": "Bananas are berries but strawberries are not.", "answer": "True"},
    {"text": "A group of flamingos is called a 'flamboyance'.", "answer": "True"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space with the naked eye.", "answer": "False"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "A shrimp's heart is in its head.", "answer": "True"},
    {"text": "Lightning never strikes the same place twice.", "answer": "False"},
    {"text": "Goldfish have a memory span of only 3 seconds.", "answer": "False"},
    {"text": "The human brain uses about 20% of the body's total energy.", "answer": "True"},
    {"text": "Penguins can fly.", "answer": "False"},
    {"text": "The shortest war in history lasted 38 minutes.", "answer": "True"},
    {"text": "A group of crows is called a 'murder'.", "answer": "True"},
    {"text": "Sharks are older than trees.", "answer": "True"},
    {"text": "The unicorn is Scotland's national animal.", "answer": "True"},
    {"text": "Cleopatra lived closer in time to the Moon landing than to the construction of the Great Pyramid.", "answer": "True"}
]
